web: 
  image: nginx
  ports: 
    - "80:80"
  volumes: 
    - /wwwroot:/wwwroot
    - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
  links: 
    - php  
php: 
  image: php:7.3.9-fpm
  volumes: 
    - /wwwroot:/wwwroot
