mysql: 
  image: fah-mysql
  environment: 
    MYSQL_ROOT_PASSWORD: "fah_xxoo_2019+-"
  ports: 
    - "3306:3306"

php-fpm: 
  image: fah-fpm
  volumes: 
    - /wwwroot:/wwwroot

web: 
  image: fah-nginx
  ports: 
    - "80:80"
  volumes: 
    - /wwwroot:/wwwroot
    - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
  links: 
    - php-fpm
